from models import SessionLocal, SystemLog
import datetime
import os

def generate_report(output_format='html'):
    db = SessionLocal()
    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        
        # Get statistics
        total_events = db.query(SystemLog).count()
        total_anomalies = db.query(SystemLog).filter(SystemLog.is_anomaly == True).count()
        high_risk_events = db.query(SystemLog).filter(SystemLog.risk_score > 70).count()
        
        # Get recent critical anomalous events
        critical_events = db.query(SystemLog).filter(
            SystemLog.is_anomaly == True, 
            SystemLog.risk_score > 60
        ).order_by(SystemLog.timestamp.desc()).limit(20).all()
        
        if output_format == 'html':
            return _write_html_report(timestamp, total_events, total_anomalies, high_risk_events, critical_events)
        else:
            return _write_text_report(timestamp, total_events, total_anomalies, high_risk_events, critical_events)
    finally:
        db.close()

def _write_html_report(timestamp, total, anomalies, high_risk, events):
    os.makedirs('reports', exist_ok=True)
    filename = f'reports/Forensic_Report_{timestamp}.html'
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Digital Forensic Investigation Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
            th {{ background-color: #f2f2f2; }}
            .summary-box {{ background-color: #f8f9fa; padding: 20px; border-radius: 5px; margin-top: 20px; }}
            .danger {{ background-color: #ffebee; color: #c62828; font-weight: bold; }}
            .footer {{ margin-top: 50px; font-size: 0.9em; color: #777; }}
        </style>
    </head>
    <body>
        <h1>Intelligent Digital Forensic Investigation Report</h1>
        <p><strong>Generated On:</strong> {timestamp.replace('_', ' ')}</p>
        
        <div class="summary-box">
            <h2>Executive Summary</h2>
            <p><strong>Total Monitored Events:</strong> {total}</p>
            <p><strong>Total Anomalous Events Detected:</strong> {anomalies}</p>
            <p><strong>High-Risk Threat Events:</strong> {high_risk}</p>
        </div>
        
        <h2>Critical Threat Timeline</h2>
        <table>
            <tr>
                <th>Timestamp</th>
                <th>Event Type</th>
                <th>Description</th>
                <th>Source</th>
                <th>Risk Score</th>
                <th>Evidence SHA256 Hash</th>
            </tr>
    """
    
    for event in events:
        risk_class = 'danger' if event.risk_score > 80 else ''
        html += f"""
            <tr class="{risk_class}">
                <td>{event.timestamp}</td>
                <td>{event.event_type}</td>
                <td>{event.description}</td>
                <td>{event.source}</td>
                <td>{event.risk_score:.1f}/100</td>
                <td style="font-family: monospace; font-size: 0.8em;">{event.hash_value}</td>
            </tr>
        """
        
    html += """
        </table>
        
        <div class="footer">
            <p>Generated by: Intelligent Forensic & Threat Detection Engine.</p>
            <p>Note: All log entries listed above have been computationally hashed via SHA-256 to ensure forensic integrity.</p>
        </div>
    </body>
    </html>
    """
    
    with open(filename, 'w') as f:
        f.write(html)
        
    return filename

def _write_text_report(timestamp, total, anomalies, high_risk, events):
    os.makedirs('reports', exist_ok=True)
    filename = f'reports/Forensic_Report_{timestamp}.txt'
    
    text = f"""======================================================
INTELLIGENT DIGITAL FORENSIC INVESTIGATION REPORT
======================================================
Generated On: {timestamp.replace('_', ' ')}

--- EXECUTIVE SUMMARY ---
Total Monitored Events:      {total}
Anomalous Events Detected:   {anomalies}
High-Risk Threat Events:     {high_risk}

--- CRITICAL THREAT TIMELINE ---
"""
    
    for event in events:
        text += f"\nTime: {event.timestamp} | Type: {event.event_type} | Risk: {event.risk_score:.1f}/100\n"
        text += f"Description: {event.description}\n"
        text += f"Source: {event.source}\n"
        text += f"Evidence Hash (SHA256): {event.hash_value}\n"
        text += "-"*50
        
    with open(filename, 'w') as f:
        f.write(text)
        
    return filename

if __name__ == "__main__":
    rep = generate_report('html')
    print(f"Report generated successfully: {rep}")
